# Generated by Django 4.2.18 on 2025-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення категорії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
    ]
