# Generated by Django 4.2.18 on 2025-01-23 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='URL обговорення'),
            preserve_default=False,
        ),
    ]
