# Generated by Django 4.2.18 on 2025-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='country',
            field=models.CharField(blank=True, choices=[('ukraine', 'Україна'), ('poland', 'Польща'), ('germany', 'Німеччина'), ('france', 'Франція')], max_length=20, verbose_name='Країна'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['created_at'], name='forum_threa_created_f1b967_idx'),
        ),
    ]
