# Generated by Django 4.2.18 on 2025-02-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_country_thread_forum_threa_created_f1b967_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='country',
        ),
    ]
