# Generated by Django 4.2.18 on 2025-02-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_thread_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Країна'),
        ),
    ]
