# Generated by Django 4.2.18 on 2025-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_thread_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='country',
            field=models.CharField(blank=True, choices=[('ukraine', 'Україна'), ('poland', 'Польща'), ('germany', 'Німеччина'), ('france', 'Франція'), ('zimbabwe', 'Зимбабве')], max_length=20, verbose_name='Країна'),
        ),
    ]
